name: inkwell-store

services:

  front-end-client:
    networks:
      - inkwell
      
  api-gateway:
    ports:
      - "8080:8080"
    networks:
      - inkwell

  authorization-service:
    networks:
      - inkwell

  customer-service:
    networks:
      - inkwell

  rabbitmq-service:
    image: rabbitmq:4.3.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - inkwell

  notification-service:
    networks:
      - inkwell

networks:
  inkwell: {}
